version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: userdb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userDb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

#docker-compose exec postgres psql -U postgres -c "CREATE DATABASE userDb;"